# hw1:成绩分析
1.计算每位学生的平均分和总分
2.找出数学成绩高于90或英语成绩高于85的学生
3.按总分从高到低排序并输出前3名学生

In [1]:
import pandas as pd
import numpy as np

In [4]:
data = {
    '姓名' :['张三', '李四', '王五', '赵六', '钱七'],
    '数学' :[85, 92, 78, 88, 95],
    '英语' :[90, 88, 85, 92, 80],
    '物理' :[75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
print(scores)

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [26]:
# 计算每人的总分与平均分
scores['总分'] = scores[['数学', '英语', '物理']].sum(axis = 1) # 计算行的和
print(scores[['姓名','总分']])
scores['平均分'] = scores['总分']/3
scores['平均分'] = scores[['数学', '英语', '物理']].mean(axis = 1)
print(scores[['姓名','平均分']])
# 找出数学高于90或英语高于85的学生
scores[(scores['数学']>90) | (scores['英语']>85)]
# 按总分从高到低排序并输出前三
scores.sort_values('总分', ascending = False).head(3)
# scores.nlargest(3,columns = '总分')同样效果

   姓名   总分
0  张三  250
1  李四  260
2  王五  251
3  赵六  265
4  钱七  265
   姓名        平均分
0  张三  83.333333
1  李四  86.666667
2  王五  83.666667
3  赵六  88.333333
4  钱七  88.333333

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

# hw2:销售数据分析
计算每种产品的总销售额, 找出销售额最高的产品, 按销售额从高到低排序并输出所有产品信息

In [28]:
data = {
    '产品名称':['A', 'B', 'C', 'D'],
    '单价':[100, 150, 200, 120],
    '销量':[50, 30, 20, 40]
}
sale = pd.DataFrame(data)
sale

  产品名称   单价  销量
0    A  100  50
1    B  150  30
2    C  200  20
3    D  120  40

In [30]:
sale['总销售额'] = sale['单价'] * sale['销量']
sale.nlargest(1, columns = ['总销售额'])
sale.sort_values('总销售额', ascending = False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000