# Pandas数据分析
完整流程:数据收集,数据清洗,数据分析,数据可视化

## 1.数据的导入与导出

In [56]:
import pandas as pd

In [57]:
# 数据导入
df1 = pd.read_csv('data_withna.csv')
print(df1)
# 数据导出
df1.to_csv('new.csv')

      name  id favorite food  height  score
0   quincy   1      hot dogs     183   78.0
1     beau   2           NaN     170   81.0
2    abbey   3         pizza     167   92.0
3  mrugesh   4      icecream     175   65.0
4      ray   5       noodles     182    NaN
5    dante   6           NaN     178   87.0
6   leader   7    hamburgers     170   98.0

In [58]:
# json
import json
with open('data.json') as f:
    data = json.load(f)
df2 = pd.DataFrame(data['users'])
print(df2)

   id  name  age  is_active
0   1   ray   21       True
1   2  jack   30      False

## 2.缺失值处理

In [59]:
# 缺失值处理
import numpy as np
s = pd.Series([12, 25, np.nan, None, pd.NA])
df = pd.DataFrame([[1,pd.NA,2], [2,3,5], [None,4,6]], 
                  columns = ['第一列','第二列','第三列'])
# 检查缺失值
print(s.isna())
print(s.isnull().sum())
print(df.isna())
print(df.isnull().sum())

0    False
1    False
2     True
3     True
4     True
dtype: bool
3
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
第一列    1
第二列    1
第三列    0
dtype: int64

In [60]:
# 剔除缺失值
print(s.dropna()) # 删除缺失值位置
print(df.dropna()) # 删除含缺失值的记录
print(df.dropna(how = 'all')) # 仅在所有值均为缺失值时删除记录
print(df.dropna(thresh = 2)) # 至少有n个值不是缺失值就保留记录
print(df.dropna(axis = 1)) # 删除整列的目录(axis取值与其他方法不同)
print(df.dropna(subset = ['第一列'])) # 仅删除指定列中存在缺失值的记录

0    12
1    25
dtype: object
   第一列 第二列  第三列
1  2.0   3    5
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第三列
0    2
1    5
2    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5

In [61]:
# 填充缺失值
df = pd.read_csv('data_withna.csv')
# 使用字典填入固定的值
print(df.fillna({'favorite food' : 'bread', 'score' : 60})) 
# 使用统计值填充
print(df.fillna({'score' : df['score'].mean()}))
# 用前方的值填充
print(df.ffill())
# 用后方的值填充
print(df.bfill())

      name  id favorite food  height  score
0   quincy   1      hot dogs     183   78.0
1     beau   2         bread     170   81.0
2    abbey   3         pizza     167   92.0
3  mrugesh   4      icecream     175   65.0
4      ray   5       noodles     182   60.0
5    dante   6         bread     178   87.0
6   leader   7    hamburgers     170   98.0
      name  id favorite food  height  score
0   quincy   1      hot dogs     183   78.0
1     beau   2           NaN     170   81.0
2    abbey   3         pizza     167   92.0
3  mrugesh   4      icecream     175   65.0
4      ray   5       noodles     182   83.5
5    dante   6           NaN     178   87.0
6   leader   7    hamburgers     170   98.0
      name  id favorite food  height  score
0   quincy   1      hot dogs     183   78.0
1     beau   2      hot dogs     170   81.0
2    abbey   3         pizza     167   92.0
3  mrugesh   4      icecream     175   65.0
4      ray   5       noodles     182   65.0
5    dante   6       noodles     178   87.0
6   leader   7    hamburgers     170   98.0
      name  id favorite food  height  score
0   quincy   1      hot dogs     183   78.0
1     beau   2         pizza     170   81.0
2    abbey   3         pizza     167   92.0
3  mrugesh   4      icecream     175   65.0
4      ray   5       noodles     182   87.0
5    dante   6    hamburgers     178   87.0
6   leader   7    hamburgers     170   98.0

## 3.重复项

In [62]:
data = {
    'name' : ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    'age' : [26, 25, 30, 25, 35, 30],
    'city' : ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [63]:
df.duplicated() # 整条记录完全相同返回True
df.drop_duplicates(subset = ['name']) # 根据指定列去重
df.drop_duplicates(subset = ['name'], keep = 'last') # 选择保留索引较大的记录

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

## 4.数据类型转换

In [64]:
df = pd.read_csv('data.csv')
df.dtypes

name             object
id                int64
favorite food    object
height            int64
score             int64
gender           object
time             object
dtype: object

In [65]:
df['score'] = df['score'].astype('int16')
df.dtypes

name             object
id                int64
favorite food    object
height            int64
score             int16
gender           object
time             object
dtype: object

In [66]:
df['gender'] = df['gender'].astype('category')
df.gender

0      male
1    female
2    female
3      male
4      male
5      male
6      male
Name: gender, dtype: category
Categories (2, object): ['female', 'male']

In [67]:
df['is_male'] = df['gender'].map({'female':False, 'male':True})
df.is_male

0     True
1    False
2    False
3     True
4     True
5     True
6     True
Name: is_male, dtype: category
Categories (2, bool): [False, True]

## 5.数据变形

In [68]:
data = {
    'id' : [1, 2],
    'name' : ['alice', 'bob'],
    'Math' : [90, 85],
    'English' : [88, 92],
    'Science' : [95, 89]
}
df = pd.DataFrame(data)
df.T
df # 宽表(列多于行)
# 宽表转换成长表
df2 = pd.melt(df, id_vars = ['id', 'name'], var_name = '科目', value_name = '分数')
df2.sort_values('name')
# id_vars:不变化的列, var_name:变化的列组成的列名, value_name:对应值的列名 
# 长表转换成宽表
pd.pivot(df2, index = ['id', 'name'], columns = '科目', values = '分数')

科目        English  Math  Science
id name
1  alice       88    90       95
2  bob         92    85       89

In [69]:
data = {
    'id' : [1, 2],
    'name' : ['alice smith', 'bob smith'],
    'Math' : [90, 85],
    'English' : [88, 92],
    'Science' : [95, 89]
}
df = pd.DataFrame(data)
# 分列
df[['first name', 'last name']] = df['name'].str.split(" ", expand = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          2 non-null      int64
 1   name        2 non-null      object
 2   Math        2 non-null      int64
 3   English     2 non-null      int64
 4   Science     2 non-null      int64
 5   first name  2 non-null      object
 6   last name   2 non-null      object
dtypes: int64(4), object(3)
memory usage: 244.0+ bytes

In [70]:
# 数据分箱 pd.cut(x, bins, labels)
df = pd.read_csv('data.csv')
df

      name  id favorite food  height  score  gender        time
0   quincy   1      hot dogs     183     78    male  2025-03-25
1     beau   2        cereal     170     81  female  2026-03-03
2    abbey   3         pizza     167     92  female  2026-01-06
3  mrugesh   4      icecream     175     65    male  2026-02-21
4      ray   5       noodles     182     95    male  2026-02-23
5    dante   6        devils     178     87    male  2026-03-02
6   leader   7    hamburgers     170     98    male  2026-03-07

In [71]:
df1 = df[['name', 'score', 'height']]
df1

      name  score  height
0   quincy     78     183
1     beau     81     170
2    abbey     92     167
3  mrugesh     65     175
4      ray     95     182
5    dante     87     178
6   leader     98     170

In [72]:
pd.cut(df1['score'], bins = 2) # bins = n:分割为n个区间,起始值为最小值,结束值是最大值
pd.cut(df1['score'], bins = 2).value_counts()
pd.cut(df1['score'], bins = [0, 60, 80, 100]) # bins = []:按列表中的数值分割
pd.cut(df1['score'], bins = [0, 60, 80, 100], labels = ['不及格', '及格', '优']) # 分割后加标签
pd.qcut(df1['height'],3).value_counts() # 等频划分
# 字符串直接转为category后统计,数值先分箱再做统计

height
(166.999, 170.0]    3
(170.0, 178.0]      2
(178.0, 183.0]      2
Name: count, dtype: int64

In [73]:
# df.rename()   df.set_index()    df.reset_index()
df = pd.DataFrame(
    {
        'name' : ['jack','alice','tom','bob'],
        'age' : [20, 30, 40, 50],
        'gender' : ['male', 'female', 'male', 'male']
    }
)
df = df.set_index('name') # set a column as the index
df.reset_index(inplace = True) # inplace = True才对当前DataFrame生效
df
df = df.rename(columns = {'age' : '年龄', 'gender' : '性别'}, index = {0 : 4})
print(df)
df.index = [1, 2, 3, 4]
df.columns = ['name', 'age', 'gender']
df

    name  年龄      性别
4   jack  20    male
1  alice  30  female
2    tom  40    male
3    bob  50    male

    name  age  gender
1   jack   20    male
2  alice   30  female
3    tom   40    male
4    bob   50    male

## 7.时间数据处理

In [74]:
d = pd.Timestamp('2015-02-28 10:22')
print(d)
print(type(d))
print('年:', d.year)
print(d.hour, d.minute, d.second)
# 季度
print(d.quarter)
print(d.is_month_end)
# methods
print(d.day_name()) # 星期几
print(d.to_period("D")) # 转换为天/季度等
print(d.to_period("Q"))
print(d.to_period("W"))

2015-02-28 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年: 2015
10 22 0
1
True
Saturday
2015-02-28
2015Q1
2015-02-23/2015-03-01

In [75]:
# str to Timestap
a = pd.to_datetime('2015-05-02 10:22')
print(a.day_name())

# DataFrame to Timestamp
df = pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime'] = pd.to_datetime(df['date'])
df
print(df.info())
# .dt: Series to Timestamp
df['dayname'] = (df['datetime'].dt.day_name())
df
df['datetime'].dt.year

Saturday
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes
None

0    2025
1    2025
2    2025
Name: datetime, dtype: int32

In [115]:
# csv
df = pd.read_csv('data.csv', parse_dates = ['time']) # 解析分析为datetime64
df['datetime'] = pd.to_datetime(df['time'])
df['datetime'].dt.day_name()

0     Tuesday
1     Tuesday
2     Tuesday
3    Saturday
4      Monday
5      Monday
6    Saturday
Name: datetime, dtype: object

In [116]:
# 日期数据作为索引
df.set_index('time', inplace = True)
df.sort_index(inplace = True)
# 这需要index有序
print(df.loc["2026-01-06":"2026-03-02"])

               name  id favorite food  height  score  gender   datetime
time
2026-01-06    abbey   3         pizza     167     92  female 2026-01-06
2026-02-21  mrugesh   4      icecream     175     65    male 2026-02-21
2026-02-23      ray   5       noodles     182     95    male 2026-02-23
2026-03-02    dante   6        devils     178     87    male 2026-03-02

In [121]:
# 时间间隔
d1 = pd.Timestamp('2026-01-06')
d2 = pd.Timestamp('2026-03-02')
d3 = d2 - d1
print(type(d3))
print(d3)

<class 'pandas._libs.tslibs.timedeltas.Timedelta'>
55 days 00:00:00

In [122]:
df = pd.read_csv('data.csv', parse_dates = ['time'])
df.sort_values(['time'], inplace = True)
df['delta']  = df['time'] - df['time'][0]
df.set_index('delta', inplace = True)
df

             name  id favorite food  height  score  gender       time
delta
0 days     quincy   1      hot dogs     183     78    male 2025-03-25
287 days    abbey   3         pizza     167     92  female 2026-01-06
333 days  mrugesh   4      icecream     175     65    male 2026-02-21
335 days      ray   5       noodles     182     95    male 2026-02-23
342 days    dante   6        devils     178     87    male 2026-03-02
343 days     beau   2        cereal     170     81  female 2026-03-03
347 days   leader   7    hamburgers     170     98    male 2026-03-07

In [124]:
df.loc['10 days':'350 days']

             name  id favorite food  height  score  gender       time
delta
287 days    abbey   3         pizza     167     92  female 2026-01-06
333 days  mrugesh   4      icecream     175     65    male 2026-02-21
335 days      ray   5       noodles     182     95    male 2026-02-23
342 days    dante   6        devils     178     87    male 2026-03-02
343 days     beau   2        cereal     170     81  female 2026-03-03
347 days   leader   7    hamburgers     170     98    male 2026-03-07

In [131]:
days = pd.date_range('2026-01-01', "2026-03-25", freq = 'D')
days = pd.date_range('2026-01-01', periods = 10, freq = 'QS')
print(days)

DatetimeIndex(['2026-01-01', '2026-04-01', '2026-07-01', '2026-10-01',
               '2027-01-01', '2027-04-01', '2027-07-01', '2027-10-01',
               '2028-01-01', '2028-04-01'],
              dtype='datetime64[ns]', freq='QS-JAN')

In [132]:
# resample
df = pd.read_csv('data.csv', parse_dates = ['time'])
df.sort_values(['time'], inplace = True)
df.set_index('time', inplace = True)
df

               name  id favorite food  height  score  gender
time
2025-03-25   quincy   1      hot dogs     183     78    male
2026-01-06    abbey   3         pizza     167     92  female
2026-02-21  mrugesh   4      icecream     175     65    male
2026-02-23      ray   5       noodles     182     95    male
2026-03-02    dante   6        devils     178     87    male
2026-03-03     beau   2        cereal     170     81  female
2026-03-07   leader   7    hamburgers     170     98    male

In [138]:
df[["score"]].resample("MS").mean()

                score
time
2025-03-01  78.000000
2025-04-01        NaN
2025-05-01        NaN
2025-06-01        NaN
2025-07-01        NaN
2025-08-01        NaN
2025-09-01        NaN
2025-10-01        NaN
2025-11-01        NaN
2025-12-01        NaN
2026-01-01  92.000000
2026-02-01  80.000000
2026-03-01  88.666667

## 8.分组聚合

In [154]:
# df.groupby('column')['target_column'].function
df = pd.read_csv('data.csv')
df.groupby('gender').groups # 查看分组
df.groupby('gender').get_group('male') # 查看特定分组
df1 = df.groupby('gender')[['score']].mean()
df1 = df1.reset_index()
df1.sort_values('score', ascending = False)
# 根据多个条件分组
df1 = df.groupby(['gender', 'height'])[['score']].mean()
df2 = df1.reset_index()
df2.sort_values('score', ascending = True)

   gender  height  score
2    male     175   76.0
0  female     170   86.5
3    male     182   86.5
1    male     170   98.0